---
- hosts: localhost
  vars:
    sitename: 'sameera'
  tasks:
    - name: install yum module
      yum:
        name: httpd
        state: latest

    - name: copy the template file to the hosts
      template:
        src: httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf
        

    - name: start the service module
#      raw: /usr/sbin/httpd -k restart
      service:
        name: httpd
        state: started
