---
- hosts: localhost
  vars:
    sitename: 'sameera' 
  tasks:
    - name: install package
      yum:
        name: httpd
        state: latest

    - name: start a service
      service:
        name: httpd
        state: started

    - name: template file
      template:
        src: httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf

    - name: template file2
      template:
        src: index.html.j2
        dest: /var/www/html

   
   
         
    
