---
- hosts: localhost
  remote_user: root
  become: no
  vars:
    variable_to_be_replaced: 'SAMEERA'
    list: [ 'dancing','singing' ]
    server_hostname: 'sameera'
    sitename: 'sameera.com'
  roles:
    - role: generate-ssl
    - role: install-apache
    - role: config-apache

